### ISSUE TITLE
Error installing via Composer - Repo not found

### ISSUE THREAD

**Issue by ux-engineer** [JasonMortonNZ/Jinput#1]
With: "jasonnz/jinput": "dev-master"

Updating dependencies (including require-dev)
- Installing jasonnz/jinput (dev-master 5bf9269)
  Cloning 5bf926910bffbcf24064a06a19238f157e42bb01
  
  [RuntimeException]  
  Failed to clone http://github.com/jasonmortonnz/jinput.git via git, https and http protocols, aborting.  
- git://github.com/jasonmortonnz/jinput.git  
  fatal: remote error:  
    Repository not found.                                                                                
- https://github.com/jasonmortonnz/jinput.git  
  fatal: Authentication failed                                                                           
- http://github.com/jasonmortonnz/jinput.git  
  fatal: Authentication failed

**Comment by JasonMortonNZ** [comment]
Should work now. All sorted I think :)
