### ISSUE TITLE
PHP-Requirements and short Array Syntax

### ISSUE THREAD

**Issue by MSchlieper** [JasonMortonNZ/Jinput#5]
Found your Jinput-Class just when I needed something like CI's XSS-Functions in a new Laravel 4 Project a couple of minutes ago. Thanks for that. ;-)

In your composer.json you are specifying a requirement of PHP >= 5.3.0 - but you are using the "new" (PHP >= 5.4) short syntax for arrays (Jinput.php, line 37).
Better to change the array declaration than to bump up the requirements, I guess...

**Comment by EdRands** [comment]
Just found this myself, and submitted a pull request.

**Comment by JasonMortonNZ** [comment]
Fixed. A composer update should update you to the latest version, compatible with PHP 5.3 now.
